spring.application.name=WarOracle

# Clash of Clans Official API Token
clash.api.token= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjIxMWEwMjI3LTYxZDYtNDBlOC04YTlkLTUxNDExN2MyM2M2ZSIsImlhdCI6MTc4OTgzMDMyOSwic3ViIjoiZGV2ZWxvcGVyLzkwYTg0MjgwLTFkNzItNGRmMy04ODk5LTQzYzc0MTZjZGYzMSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE1Mi41Ny45OS4xMDIiXSwidHlwZSI6ImNsaWVudCJ9XX0.tJ5IEvpMQGfPyukBygptcBCiCwPg_-GJqzXuE_0iofjQ9hC9HkFwkho65CmjJYaN20Czujy5uRJGbEOjRukZWw

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/waroracle?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
